/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Lastupdate = string;
export type Totalprojects = number;
export type Totalclosed = number;
export type Totalpaymentnodes = number;
export type Projects = {
  [k: string]: unknown;
}[];
export type Columns = {
  [k: string]: unknown;
}[];
export type Matched = boolean;
export type Source = string;
export type NoName = number | null;
export type NoName1 = number | null;
export type NoName2 = number | null;
export type NoName3 = number | null;
export type NoName4 = boolean | null;
export type NoName5 = boolean | null;
export type NoName6 = string | null;
export type NoName7 = number | null;
export type NoName8 = string | null;
export type NoName9 = string | null;
export type NoName10 = string | null;
export type NoName11 = number | null;
export type NoName12 = number | null;
export type NoName13 = string | null;
export type NoName14 = number | null;
export type NoName15 = string | null;
export type NoName16 = boolean | null;
export type NoName17 = string | null;
export type NoName18 = string | null;
export type NoName19 = string | null;
export type NoName20 = number | null;
export type NoName21 = string | null;
export type NoName22 = string | null;
export type NoName23 = string | null;
export type NoName24 = string | null;
export type NoName25 = string | null;
export type NoName26 = string | null;
export type NoName27 = number | null;
export type NoName28 = string | null;
export type NoName29 = string | null;
export type L4 = string | null;
export type L3 = string | null;
export type L31 = string | null;
export type Ar = string | null;
export type Sr = string | null;
export type Csr = string | null;
export type Cdr = string | null;
export type Sponsor = string | null;
export type Riskrecords = {
  [k: string]: unknown;
}[];
export type Pmisprovided = boolean;
export type Joinrate = number;
export type Matchedactive = number;
export type Matchedclosed = number;
export type Unmatched = number;
export type Lastpmisupdate = string;
export type Themes = {
  [k: string]: unknown;
}[];
export type Unmatched1 = {
  [k: string]: unknown;
}[];
export type Backfill = {
  [k: string]: unknown;
}[];
export type Conflicts = {
  [k: string]: unknown;
}[];
export type Dirty = {
  [k: string]: unknown;
}[];
export type Projectid = string;
export type Projectname = string;
export type Projectmanager = string;
export type Orgl4 = string;
export type Orgl31 = string;
export type NoName30 = string;
export type Ispresale = boolean;
export type Relatedclosedid = string;
export type Relatednodecount = number;
export type Expectedtotal = number;
export type Actualtotal = number;
export type Remainingtotal = number;
export type Paymentratio = number | null;
export type Delayedcount = number;
export type NoName31 = string;
export type NoName32 = number | null;
export type NoName33 = number | null;
export type NoName34 = number | null;
export type NoName35 = number | null;
export type Deliverycosts = DeliveryCostItem[];
export type Overspendamount = number | null;
export type Contract = number | null;
export type Actualtotal1 = number | null;
export type Paymentcount = number;
export type Expectedtotal1 = number;
export type Nodecount = number;
export type Reachedcount = number;
export type Delayedcount1 = number;
export type Lastpaymentdate = string;
export type Fromorigin = boolean;
export type Progressabnormal = boolean;
export type Riskabnormal = boolean;
export type Costabnormal = boolean;
export type Paymentabnormal = boolean;
export type Overall = string;
export type Projects1 = Project[];
export type Deptprojectcount = number;
export type Provided = boolean;
export type Rows = number;
export type Matched1 = number;
export type Matchrate = number;
export type Staffnoproject = {
  [k: string]: unknown;
}[];
export type Managernotinorg = {
  [k: string]: unknown;
}[];
export type Presaletotal = number;
export type Presalemapped = number;
export type Presaleunmapped = {
  [k: string]: unknown;
}[];
export type Name = string;
export type Plandate = string;
export type Actualdate = string;
export type Paystage = string;
export type Payratio = number | null;
export type Pct = number | null;
export type Priority = string;
export type Total = number;
export type Count = number;
export type Lastdate = string;
export type Type = string;
export type Serial = string;
export type Payer = string;
export type Amount = number | null;
export type Date = string;
export type Claimer = string;
export type Orderno = string;
export type Currency = string;
export type Rate = number | null;
export type Note = string;
export type Billtype = string;
export type Billduedate = string;
export type Billprotocol = string;
export type Records = PaymentRecord[];
export type Stage = string;
export type Category = string;
export type Plandate1 = string;
export type Actualdate1 = string;
export type Payratio1 = number | null;
export type Expectedpayment = number;
export type Receivedamount = number;
export type Unpaidamount = number;
export type Actualratio = number | null;
export type Termdays = number | null;
export type Payterm = string;
export type Reached = boolean;
export type Status = string;
export type Code = string;
export type Name1 = string;
export type Level = number;
export type Budget = number | null;
export type Estimate = number | null;
export type Final = number | null;
export type Actual = number | null;
export type Remaining = number | null;
export type Rate1 = number | null;
export type Rows1 = ProfitRow[];
export type Ssid = string;
export type Rows2 = ProfitRow[];
export type Date1 = string;
export type Type1 = string;
export type Domain = string;
export type Projectid1 = string;
export type Projectname1 = string;
export type Summary2 = string;
export type Amount1 = number | null;
export type Tone = string;
export type Events = Event[];
export type Basedate = string;
export type Advancedprojects = number;
export type Newdelayednodes = number;
export type Paymentgained = number;
export type Risknetchange = number;
export type Newoverspendprojects = number;
export type Paymentratiochange = number | null;

export interface AnalysisData {
  meta: Meta;
  projectOverview: ProjectOverview;
  naguanMap?: Naguanmap;
  naguanExclude?: Naguanexclude;
  followupRecords?: Followuprecords;
  projectPmis?: Projectpmis;
  dataQuality?: DataQuality | null;
  projects?: Projects1;
  projectsQuality?: ProjectsQuality | null;
  projectMilestones?: Projectmilestones;
  paymentRecords?: Paymentrecords;
  paymentNodes?: Paymentnodes;
  projectProfit?: Projectprofit;
  events?: Events;
  periodCompare?: PeriodCompare | null;
  tagSeed?: Tagseed;
  [k: string]: unknown;
}
export interface Meta {
  lastUpdate: Lastupdate;
  totalProjects: Totalprojects;
  totalClosed?: Totalclosed;
  totalPaymentNodes: Totalpaymentnodes;
  [k: string]: unknown;
}
export interface ProjectOverview {
  projects?: Projects;
  columns?: Columns;
  [k: string]: unknown;
}
export interface Naguanmap {
  [k: string]: boolean;
}
export interface Naguanexclude {
  [k: string]: boolean;
}
export interface Followuprecords {
  [k: string]: unknown;
}
export interface Projectpmis {
  [k: string]: ProjectPmis;
}
export interface ProjectPmis {
  matched?: Matched;
  source?: Source;
  cost?: PmisCost;
  progress?: PmisProgress;
  risk?: PmisRisk;
  status?: PmisStatus;
  customer?: PmisCustomer;
  team?: PmisTeam;
  riskRecords?: Riskrecords;
  [k: string]: unknown;
}
export interface PmisCost {
  总预算?: NoName;
  核算?: NoName1;
  剩余预算?: NoName2;
  消耗比?: NoName3;
  项目超支?: NoName4;
  交付超支?: NoName5;
  成本状态?: NoName6;
  [k: string]: unknown;
}
export interface PmisProgress {
  完工进展?: NoName7;
  里程碑进度状态?: NoName8;
  项目阶段?: NoName9;
  终验时间?: NoName10;
  [k: string]: unknown;
}
export interface PmisRisk {
  未关闭风险数?: NoName11;
  风险记录数?: NoName12;
  最高等级?: NoName13;
  闭环率?: NoName14;
  [k: string]: unknown;
}
export interface PmisStatus {
  项目状态?: NoName15;
  是否暂停?: NoName16;
  评级?: NoName17;
  项目级别?: NoName18;
  项目类型?: NoName19;
  评分?: NoName20;
  关键动作?: NoName21;
  交付物?: NoName22;
  [k: string]: unknown;
}
export interface PmisCustomer {
  最终客户?: NoName23;
  合同编号?: NoName24;
  签约单位?: NoName25;
  行业?: NoName26;
  合同总额?: NoName27;
  [k: string]: unknown;
}
export interface PmisTeam {
  项目名称?: NoName28;
  项目经理?: NoName29;
  L4部门?: L4;
  L3部门?: L3;
  L3_1部门?: L31;
  AR?: Ar;
  SR?: Sr;
  CSR?: Csr;
  CDR?: Cdr;
  Sponsor?: Sponsor;
  [k: string]: unknown;
}
export interface DataQuality {
  summary: QualitySummary;
  themes?: Themes;
  unmatched?: Unmatched1;
  backfill?: Backfill;
  conflicts?: Conflicts;
  dirty?: Dirty;
  [k: string]: unknown;
}
export interface QualitySummary {
  pmisProvided?: Pmisprovided;
  joinRate?: Joinrate;
  matchedActive?: Matchedactive;
  matchedClosed?: Matchedclosed;
  unmatched?: Unmatched;
  lastPmisUpdate?: Lastpmisupdate;
  [k: string]: unknown;
}
export interface Project {
  projectId: Projectid;
  projectName?: Projectname;
  projectManager?: Projectmanager;
  orgL4?: Orgl4;
  orgL3_1?: Orgl31;
  合同编号?: NoName30;
  isPresale?: Ispresale;
  relatedClosedId?: Relatedclosedid;
  payment?: ProjectPayment;
  deliveryCosts?: Deliverycosts;
  overspendAmount?: Overspendamount;
  paymentPmis?: ProjectPaymentPmis | null;
  health?: ProjectHealth;
  [k: string]: unknown;
}
export interface ProjectPayment {
  relatedNodeCount?: Relatednodecount;
  expectedTotal?: Expectedtotal;
  actualTotal?: Actualtotal;
  remainingTotal?: Remainingtotal;
  paymentRatio?: Paymentratio;
  delayedCount?: Delayedcount;
  [k: string]: unknown;
}
export interface DeliveryCostItem {
  类别: NoName31;
  预算金额?: NoName32;
  实际发生?: NoName33;
  剩余预算?: NoName34;
  消耗率?: NoName35;
  [k: string]: unknown;
}
export interface ProjectPaymentPmis {
  contract?: Contract;
  actualTotal?: Actualtotal1;
  paymentCount?: Paymentcount;
  expectedTotal?: Expectedtotal1;
  nodeCount?: Nodecount;
  reachedCount?: Reachedcount;
  delayedCount?: Delayedcount1;
  lastPaymentDate?: Lastpaymentdate;
  fromOrigin?: Fromorigin;
  [k: string]: unknown;
}
export interface ProjectHealth {
  progressAbnormal?: Progressabnormal;
  riskAbnormal?: Riskabnormal;
  costAbnormal?: Costabnormal;
  paymentAbnormal?: Paymentabnormal;
  overall?: Overall;
  [k: string]: unknown;
}
export interface ProjectsQuality {
  deptProjectCount?: Deptprojectcount;
  orgFile?: InputFileStat;
  mappingFile?: InputFileStat1;
  deliveryFile?: InputFileStat2;
  milestoneActive?: InputFileStat3;
  milestoneClosed?: InputFileStat4;
  paymentRecordsFile?: InputFileStat5;
  profitDirectFile?: InputFileStat6;
  profitBridgeFile?: InputFileStat7;
  budgetFile?: InputFileStat8;
  staffNoProject?: Staffnoproject;
  managerNotInOrg?: Managernotinorg;
  presaleTotal?: Presaletotal;
  presaleMapped?: Presalemapped;
  presaleUnmapped?: Presaleunmapped;
  [k: string]: unknown;
}
export interface InputFileStat {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat1 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat2 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat3 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat4 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat5 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat6 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat7 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface InputFileStat8 {
  provided?: Provided;
  rows?: Rows;
  matched?: Matched1;
  matchRate?: Matchrate;
  [k: string]: unknown;
}
export interface Projectmilestones {
  [k: string]: MilestoneItem[];
}
export interface MilestoneItem {
  name: Name;
  planDate?: Plandate;
  actualDate?: Actualdate;
  payStage?: Paystage;
  payRatio?: Payratio;
  pct?: Pct;
  priority?: Priority;
  [k: string]: unknown;
}
export interface Paymentrecords {
  [k: string]: PaymentRecordsEntry;
}
export interface PaymentRecordsEntry {
  total?: Total;
  count?: Count;
  lastDate?: Lastdate;
  records?: Records;
  [k: string]: unknown;
}
export interface PaymentRecord {
  type?: Type;
  serial?: Serial;
  payer?: Payer;
  amount?: Amount;
  date?: Date;
  claimer?: Claimer;
  orderNo?: Orderno;
  currency?: Currency;
  rate?: Rate;
  note?: Note;
  billType?: Billtype;
  billDueDate?: Billduedate;
  billProtocol?: Billprotocol;
  [k: string]: unknown;
}
export interface Paymentnodes {
  [k: string]: PaymentNodePmis[];
}
export interface PaymentNodePmis {
  stage: Stage;
  category?: Category;
  planDate?: Plandate1;
  actualDate?: Actualdate1;
  payRatio?: Payratio1;
  expectedPayment?: Expectedpayment;
  receivedAmount?: Receivedamount;
  unpaidAmount?: Unpaidamount;
  actualRatio?: Actualratio;
  termDays?: Termdays;
  payTerm?: Payterm;
  reached?: Reached;
  status?: Status;
  [k: string]: unknown;
}
export interface Projectprofit {
  [k: string]: ProjectProfit;
}
export interface ProjectProfit {
  summary?: Summary;
  rows?: Rows1;
  bridge?: BridgeProfit | null;
  [k: string]: unknown;
}
export interface Summary {
  [k: string]: number | null;
}
export interface ProfitRow {
  code: Code;
  name: Name1;
  level?: Level;
  budget?: Budget;
  estimate?: Estimate;
  final?: Final;
  actual?: Actual;
  remaining?: Remaining;
  rate?: Rate1;
  [k: string]: unknown;
}
export interface BridgeProfit {
  ssId?: Ssid;
  summary?: Summary1;
  rows?: Rows2;
  [k: string]: unknown;
}
export interface Summary1 {
  [k: string]: number | null;
}
export interface Event {
  date: Date1;
  type: Type1;
  domain: Domain;
  projectId?: Projectid1;
  projectName?: Projectname1;
  summary?: Summary2;
  prev?: unknown;
  curr?: unknown;
  amount?: Amount1;
  tone?: Tone;
  [k: string]: unknown;
}
export interface PeriodCompare {
  lastSync?: PeriodCompareEntry | null;
  lastWeek?: PeriodCompareEntry | null;
  lastMonth?: PeriodCompareEntry | null;
  [k: string]: unknown;
}
export interface PeriodCompareEntry {
  baseDate: Basedate;
  advancedProjects?: Advancedprojects;
  newDelayedNodes?: Newdelayednodes;
  paymentGained?: Paymentgained;
  riskNetChange?: Risknetchange;
  newOverspendProjects?: Newoverspendprojects;
  paymentRatioChange?: Paymentratiochange;
  [k: string]: unknown;
}
export interface Tagseed {
  [k: string]: string[];
}
