/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Periodstart = string | null;
export type Periodend = string | null;
export type Generatedat = string;
export type Rows = number;
export type Employees = number;
export type Droppedrows = number;
export type Calendarsource = string;
export type Hoursperday = number;
export type Thisbgl2 = string[];
export type Storerows = number;
export type Storestart = string | null;
export type Storeend = string | null;
export type Provided = boolean;
export type Rows1 = number;
export type Matchedcustomers = number;
export type Hasquad = boolean;
export type Hasbg = boolean;
export type Provided1 = boolean;
export type Rows2 = number;
export type Coveredlines = number;
export type Totallines = number;
export type Pending = number;
export type Calibrated = number;
export type Ambiguous = number;
export type Unmatched = number;
export type Rows3 = number;
export type Hours = number;
export type Hassupcolumn = boolean;
export type Managers = number;
export type Id = string;
export type Name = string;
export type L2 = string;
export type L3 = string;
export type L31 = string;
export type L4 = string;
export type Category = string;
export type Ismgr = boolean;
export type Roster = YitianRosterItem[];
export type D = string;
export type Workday = boolean;
export type Isoweek = string;
export type Calcweek = string;
export type Days = YitianDay[];
export type Types = string[];
export type Worktypes = string[];
export type Customers = string[];
export type Products = string[];
export type Productnames = string[];
export type Projecttypes = string[];
export type Salesl2 = string[];
export type Servicemodes = string[];
export type Custquads = string[];
export type Custbgs = string[];
export type Prodcats = string[];
export type D1 = string;
export type E = string;
export type T = number | null;
export type H = number;
export type Wt = number | null;
export type Cu = number | null;
export type Pl = number | null;
export type Pn = number | null;
export type Pt = number | null;
export type Sm = number | null;
export type Bg = number | null;
export type Wo = string;
export type Top = boolean;
export type Ok = number;
export type Iss = string[];
export type Ct = string;
export type Cq = number | null;
export type Cbg = number | null;
export type El = number | null;
export type Ls = number;
export type Ec = number | null;
export type Ch = boolean;
export type Pm = boolean;
export type Tr = number;
export type Entries = YitianEntry[];
export type I = number;
export type Codes = string[];
export type Msgs = string[];
export type Snippet = string;
export type Issues = YitianIssue[];

export interface YitianData {
  meta: YitianMeta;
  roster: Roster;
  days: Days;
  dims: YitianDims;
  entries: Entries;
  issues: Issues;
  [k: string]: unknown;
}
export interface YitianMeta {
  periodStart: Periodstart;
  periodEnd: Periodend;
  generatedAt: Generatedat;
  rows: Rows;
  employees: Employees;
  droppedRows: Droppedrows;
  calendarSource: Calendarsource;
  hoursPerDay: Hoursperday;
  thisBgL2: Thisbgl2;
  storeRows: Storerows;
  storeStart: Storestart;
  storeEnd: Storeend;
  dataReadiness: YitianReadiness;
  [k: string]: unknown;
}
export interface YitianReadiness {
  top1000: YitianReadinessTop1000;
  productCategory: YitianReadinessProductCat;
  calibration: YitianReadinessCalib;
  unattributed: YitianReadinessUnattr;
  roster: YitianReadinessRoster;
  [k: string]: unknown;
}
export interface YitianReadinessTop1000 {
  provided: Provided;
  rows: Rows1;
  matchedCustomers: Matchedcustomers;
  hasQuad: Hasquad;
  hasBg: Hasbg;
  [k: string]: unknown;
}
export interface YitianReadinessProductCat {
  provided: Provided1;
  rows: Rows2;
  coveredLines: Coveredlines;
  totalLines: Totallines;
  [k: string]: unknown;
}
export interface YitianReadinessCalib {
  pending: Pending;
  calibrated: Calibrated;
  ambiguous: Ambiguous;
  unmatched: Unmatched;
  [k: string]: unknown;
}
export interface YitianReadinessUnattr {
  rows: Rows3;
  hours: Hours;
  [k: string]: unknown;
}
export interface YitianReadinessRoster {
  hasSupColumn: Hassupcolumn;
  managers: Managers;
  [k: string]: unknown;
}
export interface YitianRosterItem {
  id: Id;
  name: Name;
  l2: L2;
  l3: L3;
  l31: L31;
  l4: L4;
  category: Category;
  isMgr: Ismgr;
  [k: string]: unknown;
}
export interface YitianDay {
  d: D;
  workday: Workday;
  isoWeek: Isoweek;
  calcWeek: Calcweek;
  [k: string]: unknown;
}
export interface YitianDims {
  types: Types;
  workTypes: Worktypes;
  customers: Customers;
  products: Products;
  productNames: Productnames;
  projectTypes: Projecttypes;
  salesL2: Salesl2;
  serviceModes: Servicemodes;
  custQuads: Custquads;
  custBgs: Custbgs;
  prodCats: Prodcats;
  [k: string]: unknown;
}
export interface YitianEntry {
  d: D1;
  e: E;
  t: T;
  h: H;
  wt: Wt;
  cu: Cu;
  pl: Pl;
  pn: Pn;
  pt: Pt;
  sm: Sm;
  bg: Bg;
  wo: Wo;
  top: Top;
  ok: Ok;
  iss: Iss;
  ct: Ct;
  cq: Cq;
  cbg: Cbg;
  el: El;
  ls: Ls;
  ec: Ec;
  ch: Ch;
  pm: Pm;
  tr: Tr;
  [k: string]: unknown;
}
export interface YitianIssue {
  i: I;
  codes: Codes;
  msgs: Msgs;
  snippet: Snippet;
  [k: string]: unknown;
}
